### PR TITLE
Perf altimetry

### PR DESCRIPTION
**Pull request by LePetitTim**
Don't update 3d geom if the geometry is the same as before

### CODE REVIEW

**Comment by camillemonchicourt** [comment]
Great ! Thanks.

**Comment by LePetitTim** [comment]
I am trying a solution to make less calcul for altimetry for example : 
- Do not calculate altimetry for all the path but only for the part modified.
- Same for event, topologies.
For elevation only 3D linestrings max and min, the calculation is not that hard but for slope, positive gain ... it is. We need to calculate for all the linestring again. If you have any suggestion it would be great.

**Comment by LePetitTim** [comment]
Trek's geometries were computed a second time even if informations were in the base in Path (e_t_troncon), now we just get the 3D part. Now changing a trek take less than 10 secs (10mins before).

**Comment by camillemonchicourt** [comment]
Wahooo

**Comment by LePetitTim** [comment]
With this modification : 30s , without 1min30 (on 1 path with 2 trails)
With : 1 s, 7 s (on 1 trek)

**Comment by camillemonchicourt** [comment]
Thanks, seems like a great improvement !

**Comment by LePetitTim** [comment]
I will try to improve the split part. Right now, we compute the altimetry for the one split but actually, a path splitted by another one do not move, this is just split so the altimetry should be compute with the previous altimetry (3D line) and not recomputed.

**Comment by LePetitTim** [comment]
Now, during the split, if we split a path really long, it doesn't recompute the path splitted.
For example : a path of 500km split with a path of 20 km take 3 minutes without
and 5 s with

**Comment by camillemonchicourt** [comment]
Still so good to hear this kind of news !

**Comment by camillemonchicourt** [comment]
Thanks, replaced by https://github.com/GeotrekCE/Geotrek-admin/pull/2195, included in version 2.33.

**Pull request closed without merging**
