### PR TITLE
Serve attachment with 'Topoguide' type as public PDF

### PR DESCRIPTION
**Pull request by gutard**

### CODE REVIEW

**Comment by camillemonchicourt** [comment]
Thanks. Cant it be mixed ? 
If some treks have no PDF attached as "Topoguide", they will have their public PDF generated automatically from template ?

**Comment by gutard** [comment]
> If some treks have no PDF attached as "Topoguide", they will have their public PDF generated automatically from template ?
By default, yes. If ONLY_EXTERNAL_PUBLIC_PDF is set, no. As requested by CD83.

**Comment by camillemonchicourt** [comment]
OK great, thanks

**Comment by JeanLenormand** [comment]
I tried this method:
1. Adding a new category called "Topoguide" in the attached files form
2. Adding a pdf to a trek as attached file
3. Launch sync = I have this message : fr api/fr/treks.geojson failed (argument 2 to map() must support iteration)

If I delete this pdf, restart the server and restart sync this error disappears.

**Comment by gutard** [comment]
Difficile de dire sans avoir plus d'info. L'erreur dans le sync a lieu pendant la génération d'un fichier .geojson, pas d'un fichier PDF. Donc a priori c'est plutôt une coïncidence.

**Comment by JeanLenormand** [comment]
Problem fixed with version 2.29.3

**Pull request merged**
