### PR TITLE
Filter trek labels according to whether they are published or not

### PR DESCRIPTION
**Pull request by Huquette**
We want to be able to filter the labels on treks according to whether the labels are published or not.

#3640

### CODE REVIEW

**Review by marcantoinedupre — APPROVED** [review]
Nice :+1:

**Review by numahell — CHANGES_REQUESTED** [review]
Nice PR, just a little suggestion :)

**Review by submarcos — COMMENTED** [review]
In other models, logic is to define published=False [by default](https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/trekking/templates/trekking/sql/post_90_defaults.sql#L84)

Maybe it is specific to labels to keep True by default

**Comment by Chatewgne** [comment]
> In other models, logic is to define published=False [by default](https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/trekking/templates/trekking/sql/post_90_defaults.sql#L84)
> 
> Maybe it is specific to labels to keep True by default

Maybe we should use "default=False" but use the migration to publish pre-existing labels so that it doesn't affect existing instances ?

**Comment by marcantoinedupre** [comment]
Either way seems fine to me. Though I have just thought that maybe `default=True` could spare us some troubles with imports from third-parties SIT.

**Review by Chatewgne — APPROVED** [review]

**Pull request merged**
