### PR TITLE
add django command to load infrastructure from shp

### PR DESCRIPTION
**Pull request by TheoLechemia**
I just adapt the `loadpoi` django command to load 'Infrastuctures' (aménagement) from a shapefile

The shapefile must have this three fields:
-name
-type
-etat

### CODE REVIEW

**Comment by camillemonchicourt** [comment]
Great but it still mention poitype. Normal ?

**Comment by TheoLechemia** [comment]
Ahhh sorry.... I forgot to change some variable names...

**Comment by camillemonchicourt** [comment]
It looks like some CODESTYLE and INTEGRATION tests failed ?

**Comment by TheoLechemia** [comment]
I'll check the codestyle since I have my serveur back...
For integration, I have no idea why ...
Someone has any idea ?

**Comment by gutard** [comment]
> For integration, I have no idea why ...
> Someone has any idea ?

You can ignore. It is allowed to fail in travis

**Comment by camillemonchicourt** [comment]
Related issue : https://github.com/GeotrekCE/Geotrek-admin/issues/952

**Comment by camillemonchicourt** [comment]
@submarcos just made the similar command to load signages : https://github.com/GeotrekCE/Geotrek-admin/commit/4da515d

Signages are a category of infrastructures, in the same table, so I dont know if these 2 commands are complementary or partially similar ?

Also here are a few ideas :

- Add a test with a sample SHP to verify that it is well imported into database
- Command fails if some fields are empty ?
- Check projection

**Comment by camillemonchicourt** [comment]
@submarcos just made the similar command to load signages : https://github.com/GeotrekCE/Geotrek-admin/commit/4da515d

Signages are a category of infrastructures, in the same table, so I dont know if these 2 commands are complementary or partially similar ?

Also here are a few ideas :

- Add a test with a sample SHP to verify that it is well imported into database
- Command fails if some fields are empty ?
- Check projection

**Comment by TheoLechemia** [comment]
If I understand well, this command is a bit more powerfull !
- You can pass the name of the related field names (type, conditions...) in the command
- It can read all formats supported by OGR (geojson, shp..)
- it reprojects the file with the good projection

They only differente I see, is the call to the ORM 
for signages `Signage.objects.create`
for infrastructures: `Infrastructure.objects.create`
but for the rest, it can be factorize in a function for example

**Pull request closed without merging**
