### PR TITLE
WIP: Add docker section in installation doc

### PR DESCRIPTION
**Pull request by numahell**
Update documentation with docker installation

### CODE REVIEW

**Comment by camillemonchicourt** [comment]
Thanks

**Comment by camillemonchicourt** [comment]
That's a great thing if Docker installation is working now. 
But in documentation I would leave manual installation first as for most of actual Geotrek users it is the easiest way to install Geotrek.

**Comment by submarcos** [comment]
It's already in docs install, but before merging All documentation must be completed and refectored

**Comment by camillemonchicourt** [comment]
OK thanks for the details.
Very interesting.

**Pull request closed without merging**
